name: go_router_sample
description: go_router sample project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  simple_logger:
  flutter_hooks:
  hooks_riverpod:
  freezed_annotation:
  go_router: ^11.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono:
  json_serializable:
  build_runner:
  freezed:
  go_router_builder: ^2.3.3

flutter:
  uses-material-design: true
