name: go_router_sample
description: go_router sample project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_logger:
  flutter_hooks:
  hooks_riverpod:
  freezed_annotation:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono:
  json_serializable:
  build_runner:
  freezed:

flutter:
  uses-material-design: true
